let shopItemsData = [
    {
    id:"caroline",
    name: "Zeus",
    price: 35,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "red-trainer.jpg",
    },
    { 
    id:"Tabs",
    name: "Jupiter",
    price: 55,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "red-shoe.jpg",
    },
    { 
    id:"Aurelia",
    name: "Ares",
    price: 30,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "green-trainer.jpg",
    },
    { 
    id:"david",
    name: "Apollo",
    price: 45,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "trainer.jpg",
    },
    { 
    id:"blackwhite",
    name: "Athena",
    price: 50,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "black+white.jpg",
    },
    { 
    id:"orangelime",
    name: "Demeter",
    price: 45,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "orange+lime.jpg",
    },
    { 
    id:"niketick",
    name: "Jupiter",
    price: 40,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "niketick.jpg",
    },
    { 
    id:"redwhite",
    name: "Mars",
    price: 50,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "red+white.jpg",
    },
    { 
    id:"orangewhite",
    name: "Minerva",
    price: 75,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "orange+white.jpg",
    },
    { 
    id:"bluewhite",
    name: "Juno",
    price: 55,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "blue+white.jpg",
    },
    { 
    id:"white",
    name: "Poseidon",
    price: 25,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "white.jpg",
    },
    { 
    id:"pinkblue",
    name: "Neptune",
    price: 60,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "pink+blue.jpg",
    }];
